import swaggerAutogen from 'swagger-autogen';

const swaggerAutoGenerate = swaggerAutogen();

const doc = {
  info: {
    version: '1.0.0',
    title: 'Express.js starter/boilerplate by @CC (CodeContinent)',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b>',
  },
  host: 'localhost:4000',
  basePath: '/api', // base endpoint for all APIs
  schemes: ['http'], // you can also add 'https' if your server is ready
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Todo',
      description: 'Endpoints for Todo API',
    },
  ],
  definitions: {
    Todo: {
      title: 'todo-item-title',
      completed: false,
      createAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
    },
    addTodo: {
      $title: 'todo-item-title',
    },
  },
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./routes/api.v1.routes.js'];

swaggerAutoGenerate(outputFile, endpointsFiles, doc);
