name: Tests

on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: TDD [Test Driven Development]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup Test Environment
        run: |
          npm install cross-env @babel/preset-env jest supertest express dotenv cors
      - name: Running Tests
        run: npm test
